/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables;


import com.yz.album.orm.Album;
import com.yz.album.orm.tables.records.HeadPictureRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HeadPicture extends TableImpl<HeadPictureRecord> {

    private static final long serialVersionUID = -1811488508;

    /**
     * The reference instance of <code>album.head_picture</code>
     */
    public static final HeadPicture HEAD_PICTURE = new HeadPicture();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HeadPictureRecord> getRecordType() {
        return HeadPictureRecord.class;
    }

    /**
     * The column <code>album.head_picture.url</code>.
     */
    public final TableField<HeadPictureRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>album.head_picture</code> table reference
     */
    public HeadPicture() {
        this("head_picture", null);
    }

    /**
     * Create an aliased <code>album.head_picture</code> table reference
     */
    public HeadPicture(String alias) {
        this(alias, HEAD_PICTURE);
    }

    private HeadPicture(String alias, Table<HeadPictureRecord> aliased) {
        this(alias, aliased, null);
    }

    private HeadPicture(String alias, Table<HeadPictureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Album.ALBUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HeadPicture as(String alias) {
        return new HeadPicture(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HeadPicture rename(String name) {
        return new HeadPicture(name, null);
    }
}
