/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables;


import com.yz.album.orm.Album;
import com.yz.album.orm.Keys;
import com.yz.album.orm.tables.records.UserAlbumReadRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAlbumRead extends TableImpl<UserAlbumReadRecord> {

    private static final long serialVersionUID = 498371463;

    /**
     * The reference instance of <code>album.user_album_read</code>
     */
    public static final UserAlbumRead USER_ALBUM_READ = new UserAlbumRead();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAlbumReadRecord> getRecordType() {
        return UserAlbumReadRecord.class;
    }

    /**
     * The column <code>album.user_album_read.id</code>.
     */
    public final TableField<UserAlbumReadRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_read.user_id</code>.
     */
    public final TableField<UserAlbumReadRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_read.album_id</code>.
     */
    public final TableField<UserAlbumReadRecord, Integer> ALBUM_ID = createField("album_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_read.last_read_time</code>.
     */
    public final TableField<UserAlbumReadRecord, Timestamp> LAST_READ_TIME = createField("last_read_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>album.user_album_read</code> table reference
     */
    public UserAlbumRead() {
        this("user_album_read", null);
    }

    /**
     * Create an aliased <code>album.user_album_read</code> table reference
     */
    public UserAlbumRead(String alias) {
        this(alias, USER_ALBUM_READ);
    }

    private UserAlbumRead(String alias, Table<UserAlbumReadRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserAlbumRead(String alias, Table<UserAlbumReadRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Album.ALBUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserAlbumReadRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_ALBUM_READ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserAlbumReadRecord> getPrimaryKey() {
        return Keys.KEY_USER_ALBUM_READ_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserAlbumReadRecord>> getKeys() {
        return Arrays.<UniqueKey<UserAlbumReadRecord>>asList(Keys.KEY_USER_ALBUM_READ_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserAlbumReadRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserAlbumReadRecord, ?>>asList(Keys.USER_ALBUM_READ_IBFK_1, Keys.USER_ALBUM_READ_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAlbumRead as(String alias) {
        return new UserAlbumRead(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAlbumRead rename(String name) {
        return new UserAlbumRead(name, null);
    }
}
