/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables;


import com.yz.album.orm.Album;
import com.yz.album.orm.Keys;
import com.yz.album.orm.tables.records.UserVipRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserVip extends TableImpl<UserVipRecord> {

    private static final long serialVersionUID = -1469100244;

    /**
     * The reference instance of <code>album.user_vip</code>
     */
    public static final UserVip USER_VIP = new UserVip();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserVipRecord> getRecordType() {
        return UserVipRecord.class;
    }

    /**
     * The column <code>album.user_vip.id</code>.
     */
    public final TableField<UserVipRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_vip.user_id</code>.
     */
    public final TableField<UserVipRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_vip.is_super_vip</code>.
     */
    public final TableField<UserVipRecord, Integer> IS_SUPER_VIP = createField("is_super_vip", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>album.user_vip.expired_time</code>.
     */
    public final TableField<UserVipRecord, Timestamp> EXPIRED_TIME = createField("expired_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>album.user_vip.create_time</code>.
     */
    public final TableField<UserVipRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>album.user_vip.update_time</code>.
     */
    public final TableField<UserVipRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>album.user_vip</code> table reference
     */
    public UserVip() {
        this("user_vip", null);
    }

    /**
     * Create an aliased <code>album.user_vip</code> table reference
     */
    public UserVip(String alias) {
        this(alias, USER_VIP);
    }

    private UserVip(String alias, Table<UserVipRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserVip(String alias, Table<UserVipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Album.ALBUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserVipRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_VIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserVipRecord> getPrimaryKey() {
        return Keys.KEY_USER_VIP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserVipRecord>> getKeys() {
        return Arrays.<UniqueKey<UserVipRecord>>asList(Keys.KEY_USER_VIP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserVipRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserVipRecord, ?>>asList(Keys.USER_VIP_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserVip as(String alias) {
        return new UserVip(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserVip rename(String name) {
        return new UserVip(name, null);
    }
}
