/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables.records;


import com.yz.album.orm.tables.Album;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlbumRecord extends UpdatableRecordImpl<AlbumRecord> implements Record10<Integer, String, String, String, String, String, Timestamp, Integer, String, Integer> {

    private static final long serialVersionUID = 81121792;

    /**
     * Setter for <code>album.album.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>album.album.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>album.album.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>album.album.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>album.album.thumbnail_url</code>.
     */
    public void setThumbnailUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>album.album.thumbnail_url</code>.
     */
    public String getThumbnailUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>album.album.breif</code>.
     */
    public void setBreif(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>album.album.breif</code>.
     */
    public String getBreif() {
        return (String) get(3);
    }

    /**
     * Setter for <code>album.album.access_type</code>. 1--&gt;黄图，2--&gt;非黄
     */
    public void setAccessType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>album.album.access_type</code>. 1--&gt;黄图，2--&gt;非黄
     */
    public String getAccessType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>album.album.is_putaway</code>.
     */
    public void setIsPutaway(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>album.album.is_putaway</code>.
     */
    public String getIsPutaway() {
        return (String) get(5);
    }

    /**
     * Setter for <code>album.album.putaway_time</code>.
     */
    public void setPutawayTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>album.album.putaway_time</code>.
     */
    public Timestamp getPutawayTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>album.album.is_banner</code>.
     */
    public void setIsBanner(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>album.album.is_banner</code>.
     */
    public Integer getIsBanner() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>album.album.channel_num</code>.
     */
    public void setChannelNum(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>album.album.channel_num</code>.
     */
    public String getChannelNum() {
        return (String) get(8);
    }

    /**
     * Setter for <code>album.album.download_time</code>.
     */
    public void setDownloadTime(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>album.album.download_time</code>.
     */
    public Integer getDownloadTime() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, Timestamp, Integer, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, Timestamp, Integer, String, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Album.ALBUM_.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Album.ALBUM_.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Album.ALBUM_.THUMBNAIL_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Album.ALBUM_.BREIF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Album.ALBUM_.ACCESS_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Album.ALBUM_.IS_PUTAWAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Album.ALBUM_.PUTAWAY_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Album.ALBUM_.IS_BANNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Album.ALBUM_.CHANNEL_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Album.ALBUM_.DOWNLOAD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getThumbnailUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getBreif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAccessType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIsPutaway();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getPutawayTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIsBanner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getChannelNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getDownloadTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlbumRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlbumRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlbumRecord value3(String value) {
        setThumbnailUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlbumRecord value4(String value) {
        setBreif(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlbumRecord value5(String value) {
        setAccessType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlbumRecord value6(String value) {
        setIsPutaway(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlbumRecord value7(Timestamp value) {
        setPutawayTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlbumRecord value8(Integer value) {
        setIsBanner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlbumRecord value9(String value) {
        setChannelNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlbumRecord value10(Integer value) {
        setDownloadTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlbumRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7, Integer value8, String value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlbumRecord
     */
    public AlbumRecord() {
        super(Album.ALBUM_);
    }

    /**
     * Create a detached, initialised AlbumRecord
     */
    public AlbumRecord(Integer id, String name, String thumbnailUrl, String breif, String accessType, String isPutaway, Timestamp putawayTime, Integer isBanner, String channelNum, Integer downloadTime) {
        super(Album.ALBUM_);

        set(0, id);
        set(1, name);
        set(2, thumbnailUrl);
        set(3, breif);
        set(4, accessType);
        set(5, isPutaway);
        set(6, putawayTime);
        set(7, isBanner);
        set(8, channelNum);
        set(9, downloadTime);
    }
}
