/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables.records;


import com.yz.album.orm.tables.Banner;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BannerRecord extends UpdatableRecordImpl<BannerRecord> implements Record9<Integer, String, String, String, Timestamp, Timestamp, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1913929387;

    /**
     * Setter for <code>album.banner.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>album.banner.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>album.banner.content_url</code>. 内容网页，可能是需要访问的详情页，或直接返回URL
     */
    public void setContentUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>album.banner.content_url</code>. 内容网页，可能是需要访问的详情页，或直接返回URL
     */
    public String getContentUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>album.banner.banner_url</code>. 广告封面
     */
    public void setBannerUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>album.banner.banner_url</code>. 广告封面
     */
    public String getBannerUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>album.banner.banner_category</code>. 广告类型:1、是套图。2、返回一个url。3是一个详情页
     */
    public void setBannerCategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>album.banner.banner_category</code>. 广告类型:1、是套图。2、返回一个url。3是一个详情页
     */
    public String getBannerCategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>album.banner.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>album.banner.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>album.banner.end_time</code>.
     */
    public void setEndTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>album.banner.end_time</code>.
     */
    public Timestamp getEndTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>album.banner.album_id</code>.
     */
    public void setAlbumId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>album.banner.album_id</code>.
     */
    public Integer getAlbumId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>album.banner.access_type</code>.
     */
    public void setAccessType(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>album.banner.access_type</code>.
     */
    public Integer getAccessType() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>album.banner.sort</code>.
     */
    public void setSort(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>album.banner.sort</code>.
     */
    public Integer getSort() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Timestamp, Timestamp, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Timestamp, Timestamp, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Banner.BANNER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Banner.BANNER.CONTENT_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Banner.BANNER.BANNER_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Banner.BANNER.BANNER_CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Banner.BANNER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Banner.BANNER.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Banner.BANNER.ALBUM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Banner.BANNER.ACCESS_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Banner.BANNER.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContentUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBannerUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getBannerCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getAlbumId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getAccessType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value2(String value) {
        setContentUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value3(String value) {
        setBannerUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value4(String value) {
        setBannerCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value6(Timestamp value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value7(Integer value) {
        setAlbumId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value8(Integer value) {
        setAccessType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value9(Integer value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BannerRecord
     */
    public BannerRecord() {
        super(Banner.BANNER);
    }

    /**
     * Create a detached, initialised BannerRecord
     */
    public BannerRecord(Integer id, String contentUrl, String bannerUrl, String bannerCategory, Timestamp createTime, Timestamp endTime, Integer albumId, Integer accessType, Integer sort) {
        super(Banner.BANNER);

        set(0, id);
        set(1, contentUrl);
        set(2, bannerUrl);
        set(3, bannerCategory);
        set(4, createTime);
        set(5, endTime);
        set(6, albumId);
        set(7, accessType);
        set(8, sort);
    }
}
