/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables.records;


import com.yz.album.orm.tables.HeadPicture;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HeadPictureRecord extends TableRecordImpl<HeadPictureRecord> implements Record1<String> {

    private static final long serialVersionUID = -550845200;

    /**
     * Setter for <code>album.head_picture.url</code>.
     */
    public void setUrl(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>album.head_picture.url</code>.
     */
    public String getUrl() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return HeadPicture.HEAD_PICTURE.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HeadPictureRecord value1(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HeadPictureRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HeadPictureRecord
     */
    public HeadPictureRecord() {
        super(HeadPicture.HEAD_PICTURE);
    }

    /**
     * Create a detached, initialised HeadPictureRecord
     */
    public HeadPictureRecord(String url) {
        super(HeadPicture.HEAD_PICTURE);

        set(0, url);
    }
}
