/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables;


import com.yz.album.orm.Album;
import com.yz.album.orm.Keys;
import com.yz.album.orm.tables.records.UserAlbumCommentPraiseRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAlbumCommentPraise extends TableImpl<UserAlbumCommentPraiseRecord> {

    private static final long serialVersionUID = 1172944114;

    /**
     * The reference instance of <code>album.user_album_comment_praise</code>
     */
    public static final UserAlbumCommentPraise USER_ALBUM_COMMENT_PRAISE = new UserAlbumCommentPraise();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAlbumCommentPraiseRecord> getRecordType() {
        return UserAlbumCommentPraiseRecord.class;
    }

    /**
     * The column <code>album.user_album_comment_praise.id</code>.
     */
    public final TableField<UserAlbumCommentPraiseRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_comment_praise.user_id</code>.
     */
    public final TableField<UserAlbumCommentPraiseRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_comment_praise.comment_id</code>.
     */
    public final TableField<UserAlbumCommentPraiseRecord, Integer> COMMENT_ID = createField("comment_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_comment_praise.create_time</code>.
     */
    public final TableField<UserAlbumCommentPraiseRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>album.user_album_comment_praise.update_time</code>.
     */
    public final TableField<UserAlbumCommentPraiseRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>album.user_album_comment_praise</code> table reference
     */
    public UserAlbumCommentPraise() {
        this("user_album_comment_praise", null);
    }

    /**
     * Create an aliased <code>album.user_album_comment_praise</code> table reference
     */
    public UserAlbumCommentPraise(String alias) {
        this(alias, USER_ALBUM_COMMENT_PRAISE);
    }

    private UserAlbumCommentPraise(String alias, Table<UserAlbumCommentPraiseRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserAlbumCommentPraise(String alias, Table<UserAlbumCommentPraiseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Album.ALBUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserAlbumCommentPraiseRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_ALBUM_COMMENT_PRAISE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserAlbumCommentPraiseRecord> getPrimaryKey() {
        return Keys.KEY_USER_ALBUM_COMMENT_PRAISE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserAlbumCommentPraiseRecord>> getKeys() {
        return Arrays.<UniqueKey<UserAlbumCommentPraiseRecord>>asList(Keys.KEY_USER_ALBUM_COMMENT_PRAISE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserAlbumCommentPraiseRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserAlbumCommentPraiseRecord, ?>>asList(Keys.USER_ALBUM_COMMENT_PRAISE_IBFK_1, Keys.USER_ALBUM_COMMENT_PRAISE_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAlbumCommentPraise as(String alias) {
        return new UserAlbumCommentPraise(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAlbumCommentPraise rename(String name) {
        return new UserAlbumCommentPraise(name, null);
    }
}
