/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables;


import com.yz.album.orm.Album;
import com.yz.album.orm.Keys;
import com.yz.album.orm.tables.records.UserAlbumPraiseRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAlbumPraise extends TableImpl<UserAlbumPraiseRecord> {

    private static final long serialVersionUID = 1032017418;

    /**
     * The reference instance of <code>album.user_album_praise</code>
     */
    public static final UserAlbumPraise USER_ALBUM_PRAISE = new UserAlbumPraise();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAlbumPraiseRecord> getRecordType() {
        return UserAlbumPraiseRecord.class;
    }

    /**
     * The column <code>album.user_album_praise.id</code>.
     */
    public final TableField<UserAlbumPraiseRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_praise.user_id</code>.
     */
    public final TableField<UserAlbumPraiseRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_praise.album_id</code>.
     */
    public final TableField<UserAlbumPraiseRecord, Integer> ALBUM_ID = createField("album_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_praise.create_time</code>.
     */
    public final TableField<UserAlbumPraiseRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>album.user_album_praise.update_time</code>.
     */
    public final TableField<UserAlbumPraiseRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>album.user_album_praise</code> table reference
     */
    public UserAlbumPraise() {
        this("user_album_praise", null);
    }

    /**
     * Create an aliased <code>album.user_album_praise</code> table reference
     */
    public UserAlbumPraise(String alias) {
        this(alias, USER_ALBUM_PRAISE);
    }

    private UserAlbumPraise(String alias, Table<UserAlbumPraiseRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserAlbumPraise(String alias, Table<UserAlbumPraiseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Album.ALBUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserAlbumPraiseRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_ALBUM_PRAISE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserAlbumPraiseRecord> getPrimaryKey() {
        return Keys.KEY_USER_ALBUM_PRAISE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserAlbumPraiseRecord>> getKeys() {
        return Arrays.<UniqueKey<UserAlbumPraiseRecord>>asList(Keys.KEY_USER_ALBUM_PRAISE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserAlbumPraiseRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserAlbumPraiseRecord, ?>>asList(Keys.USER_ALBUM_PRAISE_IBFK_1, Keys.USER_ALBUM_PRAISE_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAlbumPraise as(String alias) {
        return new UserAlbumPraise(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAlbumPraise rename(String name) {
        return new UserAlbumPraise(name, null);
    }
}
