/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables;


import com.yz.album.orm.Album;
import com.yz.album.orm.Keys;
import com.yz.album.orm.tables.records.UserAlbumCommentSubRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAlbumCommentSub extends TableImpl<UserAlbumCommentSubRecord> {

    private static final long serialVersionUID = 766699384;

    /**
     * The reference instance of <code>album.user_album_comment_sub</code>
     */
    public static final UserAlbumCommentSub USER_ALBUM_COMMENT_SUB = new UserAlbumCommentSub();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAlbumCommentSubRecord> getRecordType() {
        return UserAlbumCommentSubRecord.class;
    }

    /**
     * The column <code>album.user_album_comment_sub.id</code>.
     */
    public final TableField<UserAlbumCommentSubRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_comment_sub.user_id</code>.
     */
    public final TableField<UserAlbumCommentSubRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_comment_sub.parent_comment_id</code>.
     */
    public final TableField<UserAlbumCommentSubRecord, Integer> PARENT_COMMENT_ID = createField("parent_comment_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_album_comment_sub.at_comment_id</code>.
     */
    public final TableField<UserAlbumCommentSubRecord, Integer> AT_COMMENT_ID = createField("at_comment_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>album.user_album_comment_sub.content</code>.
     */
    public final TableField<UserAlbumCommentSubRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>album.user_album_comment_sub.create_time</code>.
     */
    public final TableField<UserAlbumCommentSubRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>album.user_album_comment_sub.update_time</code>.
     */
    public final TableField<UserAlbumCommentSubRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>album.user_album_comment_sub</code> table reference
     */
    public UserAlbumCommentSub() {
        this("user_album_comment_sub", null);
    }

    /**
     * Create an aliased <code>album.user_album_comment_sub</code> table reference
     */
    public UserAlbumCommentSub(String alias) {
        this(alias, USER_ALBUM_COMMENT_SUB);
    }

    private UserAlbumCommentSub(String alias, Table<UserAlbumCommentSubRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserAlbumCommentSub(String alias, Table<UserAlbumCommentSubRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Album.ALBUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserAlbumCommentSubRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_ALBUM_COMMENT_SUB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserAlbumCommentSubRecord> getPrimaryKey() {
        return Keys.KEY_USER_ALBUM_COMMENT_SUB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserAlbumCommentSubRecord>> getKeys() {
        return Arrays.<UniqueKey<UserAlbumCommentSubRecord>>asList(Keys.KEY_USER_ALBUM_COMMENT_SUB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserAlbumCommentSubRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserAlbumCommentSubRecord, ?>>asList(Keys.USER_ALBUM_COMMENT_SUB_IBFK_2, Keys.USER_ALBUM_COMMENT_SUB_IBFK_3, Keys.USER_ALBUM_COMMENT_SUB_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAlbumCommentSub as(String alias) {
        return new UserAlbumCommentSub(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAlbumCommentSub rename(String name) {
        return new UserAlbumCommentSub(name, null);
    }
}
