/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables;


import com.yz.album.orm.Album;
import com.yz.album.orm.Keys;
import com.yz.album.orm.tables.records.UserSearchKeywordRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSearchKeyword extends TableImpl<UserSearchKeywordRecord> {

    private static final long serialVersionUID = 130504423;

    /**
     * The reference instance of <code>album.user_search_keyword</code>
     */
    public static final UserSearchKeyword USER_SEARCH_KEYWORD = new UserSearchKeyword();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserSearchKeywordRecord> getRecordType() {
        return UserSearchKeywordRecord.class;
    }

    /**
     * The column <code>album.user_search_keyword.id</code>.
     */
    public final TableField<UserSearchKeywordRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_search_keyword.user_id</code>.
     */
    public final TableField<UserSearchKeywordRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.user_search_keyword.keyword</code>.
     */
    public final TableField<UserSearchKeywordRecord, String> KEYWORD = createField("keyword", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>album.user_search_keyword.create_time</code>.
     */
    public final TableField<UserSearchKeywordRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>album.user_search_keyword</code> table reference
     */
    public UserSearchKeyword() {
        this("user_search_keyword", null);
    }

    /**
     * Create an aliased <code>album.user_search_keyword</code> table reference
     */
    public UserSearchKeyword(String alias) {
        this(alias, USER_SEARCH_KEYWORD);
    }

    private UserSearchKeyword(String alias, Table<UserSearchKeywordRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserSearchKeyword(String alias, Table<UserSearchKeywordRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Album.ALBUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserSearchKeywordRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_SEARCH_KEYWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserSearchKeywordRecord> getPrimaryKey() {
        return Keys.KEY_USER_SEARCH_KEYWORD_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserSearchKeywordRecord>> getKeys() {
        return Arrays.<UniqueKey<UserSearchKeywordRecord>>asList(Keys.KEY_USER_SEARCH_KEYWORD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserSearchKeywordRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserSearchKeywordRecord, ?>>asList(Keys.USER_SEARCH_KEYWORD_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSearchKeyword as(String alias) {
        return new UserSearchKeyword(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSearchKeyword rename(String name) {
        return new UserSearchKeyword(name, null);
    }
}
