/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables.records;


import com.yz.album.orm.tables.UserPay;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPayRecord extends UpdatableRecordImpl<UserPayRecord> implements Record9<Integer, Integer, Double, String, String, Timestamp, String, String, String> {

    private static final long serialVersionUID = 2041886490;

    /**
     * Setter for <code>album.user_pay.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>album.user_pay.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>album.user_pay.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>album.user_pay.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>album.user_pay.pay_amount</code>.
     */
    public void setPayAmount(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>album.user_pay.pay_amount</code>.
     */
    public Double getPayAmount() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>album.user_pay.meal_info</code>.
     */
    public void setMealInfo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>album.user_pay.meal_info</code>.
     */
    public String getMealInfo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>album.user_pay.channel_num</code>.
     */
    public void setChannelNum(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>album.user_pay.channel_num</code>.
     */
    public String getChannelNum() {
        return (String) get(4);
    }

    /**
     * Setter for <code>album.user_pay.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>album.user_pay.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>album.user_pay.payment_status</code>.
     */
    public void setPaymentStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>album.user_pay.payment_status</code>.
     */
    public String getPaymentStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>album.user_pay.payment_id</code>.
     */
    public void setPaymentId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>album.user_pay.payment_id</code>.
     */
    public String getPaymentId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>album.user_pay.charge_channel</code>.
     */
    public void setChargeChannel(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>album.user_pay.charge_channel</code>.
     */
    public String getChargeChannel() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Double, String, String, Timestamp, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Double, String, String, Timestamp, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserPay.USER_PAY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserPay.USER_PAY.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return UserPay.USER_PAY.PAY_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserPay.USER_PAY.MEAL_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UserPay.USER_PAY.CHANNEL_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return UserPay.USER_PAY.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UserPay.USER_PAY.PAYMENT_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return UserPay.USER_PAY.PAYMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return UserPay.USER_PAY.CHARGE_CHANNEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getPayAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMealInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getChannelNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPaymentStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getChargeChannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPayRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPayRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPayRecord value3(Double value) {
        setPayAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPayRecord value4(String value) {
        setMealInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPayRecord value5(String value) {
        setChannelNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPayRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPayRecord value7(String value) {
        setPaymentStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPayRecord value8(String value) {
        setPaymentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPayRecord value9(String value) {
        setChargeChannel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPayRecord values(Integer value1, Integer value2, Double value3, String value4, String value5, Timestamp value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPayRecord
     */
    public UserPayRecord() {
        super(UserPay.USER_PAY);
    }

    /**
     * Create a detached, initialised UserPayRecord
     */
    public UserPayRecord(Integer id, Integer userId, Double payAmount, String mealInfo, String channelNum, Timestamp createTime, String paymentStatus, String paymentId, String chargeChannel) {
        super(UserPay.USER_PAY);

        set(0, id);
        set(1, userId);
        set(2, payAmount);
        set(3, mealInfo);
        set(4, channelNum);
        set(5, createTime);
        set(6, paymentStatus);
        set(7, paymentId);
        set(8, chargeChannel);
    }
}
