/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm;


import com.yz.album.orm.tables.AlbumCategory;
import com.yz.album.orm.tables.AlbumPicture;
import com.yz.album.orm.tables.Banner;
import com.yz.album.orm.tables.Category;
import com.yz.album.orm.tables.Essenceurl;
import com.yz.album.orm.tables.HeadPicture;
import com.yz.album.orm.tables.LoginLog;
import com.yz.album.orm.tables.Picture;
import com.yz.album.orm.tables.StatisticsTemp;
import com.yz.album.orm.tables.User;
import com.yz.album.orm.tables.UserAlbumComment;
import com.yz.album.orm.tables.UserAlbumCommentPraise;
import com.yz.album.orm.tables.UserAlbumCommentSub;
import com.yz.album.orm.tables.UserAlbumFavorite;
import com.yz.album.orm.tables.UserAlbumPraise;
import com.yz.album.orm.tables.UserAlbumRead;
import com.yz.album.orm.tables.UserComplaint;
import com.yz.album.orm.tables.UserPay;
import com.yz.album.orm.tables.UserSearchKeyword;
import com.yz.album.orm.tables.UserVip;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Album extends SchemaImpl {

    private static final long serialVersionUID = 1152131716;

    /**
     * The reference instance of <code>album</code>
     */
    public static final Album ALBUM = new Album();

    /**
     * The table <code>album.album</code>.
     */
    public final com.yz.album.orm.tables.Album ALBUM_ = com.yz.album.orm.tables.Album.ALBUM_;

    /**
     * The table <code>album.album_category</code>.
     */
    public final AlbumCategory ALBUM_CATEGORY = com.yz.album.orm.tables.AlbumCategory.ALBUM_CATEGORY;

    /**
     * The table <code>album.album_picture</code>.
     */
    public final AlbumPicture ALBUM_PICTURE = com.yz.album.orm.tables.AlbumPicture.ALBUM_PICTURE;

    /**
     * The table <code>album.banner</code>.
     */
    public final Banner BANNER = com.yz.album.orm.tables.Banner.BANNER;

    /**
     * The table <code>album.category</code>.
     */
    public final Category CATEGORY = com.yz.album.orm.tables.Category.CATEGORY;

    /**
     * The table <code>album.essenceurl</code>.
     */
    public final Essenceurl ESSENCEURL = com.yz.album.orm.tables.Essenceurl.ESSENCEURL;

    /**
     * The table <code>album.head_picture</code>.
     */
    public final HeadPicture HEAD_PICTURE = com.yz.album.orm.tables.HeadPicture.HEAD_PICTURE;

    /**
     * The table <code>album.login_log</code>.
     */
    public final LoginLog LOGIN_LOG = com.yz.album.orm.tables.LoginLog.LOGIN_LOG;

    /**
     * The table <code>album.picture</code>.
     */
    public final Picture PICTURE = com.yz.album.orm.tables.Picture.PICTURE;

    /**
     * The table <code>album.statistics_temp</code>.
     */
    public final StatisticsTemp STATISTICS_TEMP = com.yz.album.orm.tables.StatisticsTemp.STATISTICS_TEMP;

    /**
     * The table <code>album.user</code>.
     */
    public final User USER = com.yz.album.orm.tables.User.USER;

    /**
     * The table <code>album.user_album_comment</code>.
     */
    public final UserAlbumComment USER_ALBUM_COMMENT = com.yz.album.orm.tables.UserAlbumComment.USER_ALBUM_COMMENT;

    /**
     * The table <code>album.user_album_comment_praise</code>.
     */
    public final UserAlbumCommentPraise USER_ALBUM_COMMENT_PRAISE = com.yz.album.orm.tables.UserAlbumCommentPraise.USER_ALBUM_COMMENT_PRAISE;

    /**
     * The table <code>album.user_album_comment_sub</code>.
     */
    public final UserAlbumCommentSub USER_ALBUM_COMMENT_SUB = com.yz.album.orm.tables.UserAlbumCommentSub.USER_ALBUM_COMMENT_SUB;

    /**
     * The table <code>album.user_album_favorite</code>.
     */
    public final UserAlbumFavorite USER_ALBUM_FAVORITE = com.yz.album.orm.tables.UserAlbumFavorite.USER_ALBUM_FAVORITE;

    /**
     * The table <code>album.user_album_praise</code>.
     */
    public final UserAlbumPraise USER_ALBUM_PRAISE = com.yz.album.orm.tables.UserAlbumPraise.USER_ALBUM_PRAISE;

    /**
     * The table <code>album.user_album_read</code>.
     */
    public final UserAlbumRead USER_ALBUM_READ = com.yz.album.orm.tables.UserAlbumRead.USER_ALBUM_READ;

    /**
     * The table <code>album.user_complaint</code>.
     */
    public final UserComplaint USER_COMPLAINT = com.yz.album.orm.tables.UserComplaint.USER_COMPLAINT;

    /**
     * The table <code>album.user_pay</code>.
     */
    public final UserPay USER_PAY = com.yz.album.orm.tables.UserPay.USER_PAY;

    /**
     * The table <code>album.user_search_keyword</code>.
     */
    public final UserSearchKeyword USER_SEARCH_KEYWORD = com.yz.album.orm.tables.UserSearchKeyword.USER_SEARCH_KEYWORD;

    /**
     * The table <code>album.user_vip</code>.
     */
    public final UserVip USER_VIP = com.yz.album.orm.tables.UserVip.USER_VIP;

    /**
     * No further instances allowed
     */
    private Album() {
        super("album", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            com.yz.album.orm.tables.Album.ALBUM_,
            AlbumCategory.ALBUM_CATEGORY,
            AlbumPicture.ALBUM_PICTURE,
            Banner.BANNER,
            Category.CATEGORY,
            Essenceurl.ESSENCEURL,
            HeadPicture.HEAD_PICTURE,
            LoginLog.LOGIN_LOG,
            Picture.PICTURE,
            StatisticsTemp.STATISTICS_TEMP,
            User.USER,
            UserAlbumComment.USER_ALBUM_COMMENT,
            UserAlbumCommentPraise.USER_ALBUM_COMMENT_PRAISE,
            UserAlbumCommentSub.USER_ALBUM_COMMENT_SUB,
            UserAlbumFavorite.USER_ALBUM_FAVORITE,
            UserAlbumPraise.USER_ALBUM_PRAISE,
            UserAlbumRead.USER_ALBUM_READ,
            UserComplaint.USER_COMPLAINT,
            UserPay.USER_PAY,
            UserSearchKeyword.USER_SEARCH_KEYWORD,
            UserVip.USER_VIP);
    }
}
