/*
 * This file is generated by jOOQ.
*/
package com.yz.album.orm.tables;


import com.yz.album.orm.Album;
import com.yz.album.orm.Keys;
import com.yz.album.orm.tables.records.StatisticsTempRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatisticsTemp extends TableImpl<StatisticsTempRecord> {

    private static final long serialVersionUID = -650600713;

    /**
     * The reference instance of <code>album.statistics_temp</code>
     */
    public static final StatisticsTemp STATISTICS_TEMP = new StatisticsTemp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StatisticsTempRecord> getRecordType() {
        return StatisticsTempRecord.class;
    }

    /**
     * The column <code>album.statistics_temp.id</code>.
     */
    public final TableField<StatisticsTempRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.channel_num</code>. 渠道号
     */
    public final TableField<StatisticsTempRecord, String> CHANNEL_NUM = createField("channel_num", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "渠道号");

    /**
     * The column <code>album.statistics_temp.added_user_count</code>. 新增用户数
     */
    public final TableField<StatisticsTempRecord, Integer> ADDED_USER_COUNT = createField("added_user_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "新增用户数");

    /**
     * The column <code>album.statistics_temp.new_user_active_count</code>. 新用户活跃数
     */
    public final TableField<StatisticsTempRecord, Integer> NEW_USER_ACTIVE_COUNT = createField("new_user_active_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "新用户活跃数");

    /**
     * The column <code>album.statistics_temp.old_user_active_count</code>. 老用户活跃数
     */
    public final TableField<StatisticsTempRecord, Integer> OLD_USER_ACTIVE_COUNT = createField("old_user_active_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "老用户活跃数");

    /**
     * The column <code>album.statistics_temp.keep_user_day_2</code>. 次日留存
     */
    public final TableField<StatisticsTempRecord, Integer> KEEP_USER_DAY_2 = createField("keep_user_day_2", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "次日留存");

    /**
     * The column <code>album.statistics_temp.keep_user_day_3</code>. 三日留存
     */
    public final TableField<StatisticsTempRecord, Integer> KEEP_USER_DAY_3 = createField("keep_user_day_3", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "三日留存");

    /**
     * The column <code>album.statistics_temp.keep_user_day_7</code>. 七日留存
     */
    public final TableField<StatisticsTempRecord, Integer> KEEP_USER_DAY_7 = createField("keep_user_day_7", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "七日留存");

    /**
     * The column <code>album.statistics_temp.keep_user_day_15</code>. 十五日留存
     */
    public final TableField<StatisticsTempRecord, Integer> KEEP_USER_DAY_15 = createField("keep_user_day_15", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "十五日留存");

    /**
     * The column <code>album.statistics_temp.keep_user_day_2_percent</code>.
     */
    public final TableField<StatisticsTempRecord, Double> KEEP_USER_DAY_2_PERCENT = createField("keep_user_day_2_percent", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.keep_user_day_3_percent</code>.
     */
    public final TableField<StatisticsTempRecord, Double> KEEP_USER_DAY_3_PERCENT = createField("keep_user_day_3_percent", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.keep_user_day_7_percent</code>.
     */
    public final TableField<StatisticsTempRecord, Double> KEEP_USER_DAY_7_PERCENT = createField("keep_user_day_7_percent", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.keep_user_day_15_percent</code>.
     */
    public final TableField<StatisticsTempRecord, Double> KEEP_USER_DAY_15_PERCENT = createField("keep_user_day_15_percent", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.vip1_pay_count_n</code>. 新用户（VIP1）付费次数
     */
    public final TableField<StatisticsTempRecord, Integer> VIP1_PAY_COUNT_N = createField("vip1_pay_count_n", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "新用户（VIP1）付费次数");

    /**
     * The column <code>album.statistics_temp.vip1_pay_user_count_n</code>. 新用户（VIP1）付费人数
     */
    public final TableField<StatisticsTempRecord, Integer> VIP1_PAY_USER_COUNT_N = createField("vip1_pay_user_count_n", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "新用户（VIP1）付费人数");

    /**
     * The column <code>album.statistics_temp.vip1_pay_amount_n</code>. 新用户（VIP1）总金额
     */
    public final TableField<StatisticsTempRecord, Double> VIP1_PAY_AMOUNT_N = createField("vip1_pay_amount_n", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "新用户（VIP1）总金额");

    /**
     * The column <code>album.statistics_temp.vip1_pay_count_o</code>. 老用户（VIP1）付费次数
     */
    public final TableField<StatisticsTempRecord, Integer> VIP1_PAY_COUNT_O = createField("vip1_pay_count_o", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "老用户（VIP1）付费次数");

    /**
     * The column <code>album.statistics_temp.vip1_pay_user_count_o</code>.
     */
    public final TableField<StatisticsTempRecord, Integer> VIP1_PAY_USER_COUNT_O = createField("vip1_pay_user_count_o", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.vip1_pay_amount_o</code>.
     */
    public final TableField<StatisticsTempRecord, Double> VIP1_PAY_AMOUNT_O = createField("vip1_pay_amount_o", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.vip2_pay_count_n</code>.
     */
    public final TableField<StatisticsTempRecord, Integer> VIP2_PAY_COUNT_N = createField("vip2_pay_count_n", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.vip2_pay_user_count_n</code>.
     */
    public final TableField<StatisticsTempRecord, Integer> VIP2_PAY_USER_COUNT_N = createField("vip2_pay_user_count_n", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.vip2_pay_amount_n</code>.
     */
    public final TableField<StatisticsTempRecord, Double> VIP2_PAY_AMOUNT_N = createField("vip2_pay_amount_n", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.vip2_pay_count_o</code>.
     */
    public final TableField<StatisticsTempRecord, Integer> VIP2_PAY_COUNT_O = createField("vip2_pay_count_o", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.vip2_pay_user_count_o</code>.
     */
    public final TableField<StatisticsTempRecord, Integer> VIP2_PAY_USER_COUNT_O = createField("vip2_pay_user_count_o", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.vip2_pay_amount_o</code>.
     */
    public final TableField<StatisticsTempRecord, Double> VIP2_PAY_AMOUNT_O = createField("vip2_pay_amount_o", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>album.statistics_temp.create_time</code>.
     */
    public final TableField<StatisticsTempRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>album.statistics_temp</code> table reference
     */
    public StatisticsTemp() {
        this("statistics_temp", null);
    }

    /**
     * Create an aliased <code>album.statistics_temp</code> table reference
     */
    public StatisticsTemp(String alias) {
        this(alias, STATISTICS_TEMP);
    }

    private StatisticsTemp(String alias, Table<StatisticsTempRecord> aliased) {
        this(alias, aliased, null);
    }

    private StatisticsTemp(String alias, Table<StatisticsTempRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Album.ALBUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StatisticsTempRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STATISTICS_TEMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StatisticsTempRecord> getPrimaryKey() {
        return Keys.KEY_STATISTICS_TEMP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StatisticsTempRecord>> getKeys() {
        return Arrays.<UniqueKey<StatisticsTempRecord>>asList(Keys.KEY_STATISTICS_TEMP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatisticsTemp as(String alias) {
        return new StatisticsTemp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StatisticsTemp rename(String name) {
        return new StatisticsTemp(name, null);
    }
}
